# Generated by Django 5.1.2 on 2024-11-17 13:33

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'invalid': 'Please enter a valid Iranian phone number.'}, max_length=128, null=True, region='IR'),
        ),
    ]
