# Generated by Django 5.2.9 on 2026-01-01 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_comment"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="comment",
            new_name="core_commen_content_9a4d39_idx",
            old_name="core_commen_content_idx",
        ),
        migrations.RenameIndex(
            model_name="comment",
            new_name="core_commen_user_id_98f009_idx",
            old_name="core_commen_user_id_idx",
        ),
        migrations.RenameIndex(
            model_name="comment",
            new_name="core_commen_is_appr_cb047b_idx",
            old_name="core_commen_is_appr_idx",
        ),
    ]
