# Generated by Django 5.1.2 on 2024-11-11 15:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_template', models.BooleanField(default=False)),
                ('activity_type', models.CharField(choices=[('WRITE_FOR_DRAWING', 'Write for Drawing'), ('ILLUSTRATE', 'Illustrate Story'), ('COMPLETE_STORY', 'Complete Story')], default='WRITE_FOR_DRAWING', max_length=20)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='StoryCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoryPart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('text', models.TextField()),
                ('illustration', models.ImageField(blank=True, null=True, upload_to='illustrations/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='StoryPartTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('prompt_text', models.TextField()),
                ('illustration', models.ImageField(blank=True, null=True, upload_to='template_illustrations/')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='StoryTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('activity_type', models.CharField(choices=[('WRITE_FOR_DRAWING', 'Write for Drawing'), ('ILLUSTRATE', 'Illustrate Story'), ('COMPLETE_STORY', 'Complete Story')], max_length=20)),
            ],
        ),
    ]
