# Generated by Django 5.1.2 on 2024-11-17 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='is_template',
        ),
        migrations.AddField(
            model_name='story',
            name='story_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stories', to='stories.storytemplate'),
        ),
        migrations.AddField(
            model_name='storypart',
            name='story_part_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stories', to='stories.storyparttemplate'),
        ),
    ]
