# Generated by Django 5.1.7 on 2025-04-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0004_imageasset"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="background_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="stories/backgrounds/"
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="stories/covers/"),
        ),
        migrations.AddField(
            model_name="storytemplate",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="story_templates/covers/"
            ),
        ),
    ]
