# Generated by Django 5.2.1 on 2025-11-02 15:42

import stories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0006_remove_story_background_image_add_colors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="background_color",
            field=models.CharField(
                blank=True,
                help_text="Hex color code (e.g., #FF5733 or #FFF)",
                max_length=7,
                null=True,
                validators=[stories.models.validate_hex_color],
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="font_color",
            field=models.CharField(
                blank=True,
                help_text="Hex color code for text (e.g., #000000 or #000)",
                max_length=7,
                null=True,
                validators=[stories.models.validate_hex_color],
            ),
        ),
    ]
