# Generated by Django 5.2.1 on 2025-11-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0007_alter_story_background_color_alter_story_font_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("COMPLETED", "Completed")],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
