# Generated by Django 5.2.1 on 2025-12-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0008_story_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="orientation",
            field=models.CharField(
                blank=True,
                choices=[("LANDSCAPE", "Landscape"), ("PORTRAIT", "Portrait")],
                help_text="Story orientation (Landscape or Portrait)",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[("20x20", "20x20"), ("25x25", "25x25"), ("15x23", "15x23")],
                help_text="Story size (20x20, 25x25, or 15x23)",
                max_length=10,
                null=True,
            ),
        ),
    ]
