# Generated by Django 5.2.1 on 2025-12-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0010_storytemplate_orientation_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="storypart",
            name="canvas_data",
            field=models.JSONField(
                blank=True,
                help_text="Canvas data for this story part (alternative to text)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="storyparttemplate",
            name="canvas_data",
            field=models.JSONField(
                blank=True,
                help_text="Canvas data for this story part template",
                null=True,
            ),
        ),
    ]
