# Generated by Django 5.2.1 on 2025-12-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0010_storytemplate_orientation_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="canvas_data",
            field=models.JSONField(
                blank=True,
                help_text="Canvas data for stories with canvas content (alternative to text-based parts)",
                null=True,
            ),
        ),
    ]
