# Generated by Claude Code on 2025-12-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0011_add_canvas_data_to_parts"),
    ]

    operations = [
        # Remove old fields from StoryPartTemplate
        migrations.RemoveField(
            model_name="storyparttemplate",
            name="prompt_text",
        ),
        migrations.RemoveField(
            model_name="storyparttemplate",
            name="illustration",
        ),
        migrations.RemoveField(
            model_name="storyparttemplate",
            name="canvas_data",
        ),
        # Add new canvas fields to StoryPartTemplate
        migrations.AddField(
            model_name="storyparttemplate",
            name="canvas_text_template",
            field=models.JSONField(
                blank=True,
                help_text="Canvas JSON data for the text canvas template",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="storyparttemplate",
            name="canvas_illustration_template",
            field=models.JSONField(
                blank=True,
                help_text="Canvas JSON data for the illustration canvas template",
                null=True,
            ),
        ),
        # Remove old fields from StoryPart
        migrations.RemoveField(
            model_name="storypart",
            name="text",
        ),
        migrations.RemoveField(
            model_name="storypart",
            name="illustration",
        ),
        migrations.RemoveField(
            model_name="storypart",
            name="canvas_data",
        ),
        # Add new canvas fields to StoryPart
        migrations.AddField(
            model_name="storypart",
            name="canvas_text_data",
            field=models.JSONField(
                blank=True,
                help_text="Canvas JSON data for the text canvas (user editable)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="storypart",
            name="canvas_illustration_data",
            field=models.JSONField(
                blank=True,
                help_text="Canvas JSON data for the illustration canvas (user editable)",
                null=True,
            ),
        ),
    ]
