# Generated by Django 5.2.9 on 2026-01-01 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0013_templateimage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="templateimage",
            new_name="stories_tem_templat_d27329_idx",
            old_name="stories_tem_templat_idx",
        ),
        migrations.AddIndex(
            model_name="story",
            index=models.Index(
                fields=["author", "status"], name="story_author_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="story",
            index=models.Index(
                fields=["status", "-created_date"], name="story_status_date_idx"
            ),
        ),
    ]
