# Generated by Django 5.1.4 on 2024-12-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='alternative_titles',
            field=models.TextField(blank=True, help_text='Enter alternative titles separated by commas'),
        ),
    ]
