# Generated by Django 5.1.4 on 2025-01-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blogpost_alternative_titles"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="featured",
            field=models.BooleanField(
                default=False, help_text="Only one blog post can be featured at a time"
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="reading_time",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
