# Generated by Django 5.1.4 on 2025-01-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_blogpost_featured_blogpost_reading_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="hero",
            field=models.BooleanField(
                default=False, help_text="Only one blog post can be the hero at a time"
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="featured",
            field=models.BooleanField(default=False),
        ),
    ]
