# Generated by Django 5.1.7 on 2025-04-19 16:34

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_blogcategory_blogpost_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="categories",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, related_name="blogposts", to="blog.blogcategory"
            ),
        ),
    ]
