# Generated by Django 5.1.7 on 2025-04-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_blogpost_related_posts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="intro",
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="subtitle",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
