# Generated by Django 5.2.1 on 2025-11-02 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_blogpost_intro_alter_blogpost_subtitle"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogcategory",
            name="meta_description",
            field=models.TextField(
                blank=True,
                help_text="SEO description for category page (150-160 characters recommended)",
            ),
        ),
        migrations.AddField(
            model_name="blogcategory",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="SEO title for category page (50-60 characters recommended)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="canonical_url",
            field=models.URLField(
                blank=True,
                help_text="Canonical URL if content exists elsewhere",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="excerpt",
            field=models.TextField(
                blank=True,
                help_text="Short summary for post previews (150-200 characters).",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="featured_snippet",
            field=models.TextField(
                blank=True,
                help_text="Optimized content for Google featured snippets (40-60 words)",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="noindex",
            field=models.BooleanField(
                default=False,
                help_text="Prevent search engines from indexing this post",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Custom Open Graph image for social media sharing. Falls back to header_image if not provided.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="word_count",
            field=models.PositiveIntegerField(
                blank=True, default=0, help_text="Auto-calculated from body content"
            ),
        ),
    ]
