# Generated by Django 5.1.4 on 2025-01-29 17:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CART", "Cart"),
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("CONFIRMED", "Confirmed"),
                            ("SHIPPED", "Shipped"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                            ("REFUNDED", "Refunded"),
                            ("RETURNED", "Returned"),
                        ],
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="Total Amount"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("IRR", "Iranian Rial"), ("IRT", "Iranian Toman")],
                        default="IRR",
                        max_length=3,
                        verbose_name="Currency",
                    ),
                ),
                ("shipping_address", models.TextField(verbose_name="Shipping Address")),
                (
                    "phone_number",
                    models.CharField(max_length=15, verbose_name="Phone Number"),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Invoice Number"
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="invoices/pdfs/",
                        verbose_name="PDF File",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="Price"
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0, verbose_name="Stock")),
                (
                    "sku",
                    models.CharField(max_length=50, unique=True, verbose_name="SKU"),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Is Available"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="Slug"),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Meta Title"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, verbose_name="Meta Description"),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product_title",
                    models.CharField(max_length=200, verbose_name="Product Title"),
                ),
                (
                    "product_sku",
                    models.CharField(max_length=50, verbose_name="Product SKU"),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Quantity")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="Price"
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="shop.invoice",
                        verbose_name="Invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Item",
                "verbose_name_plural": "Invoice Items",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CART", "Cart"),
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("CONFIRMED", "Confirmed"),
                            ("SHIPPED", "Shipped"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                            ("REFUNDED", "Refunded"),
                            ("RETURNED", "Returned"),
                        ],
                        default="CART",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("IRR", "Iranian Rial"), ("IRT", "Iranian Toman")],
                        default="IRR",
                        max_length=3,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="Total Amount",
                    ),
                ),
                ("shipping_address", models.TextField(verbose_name="Shipping Address")),
                (
                    "phone_number",
                    models.CharField(max_length=15, verbose_name="Phone Number"),
                ),
                ("note", models.TextField(blank=True, verbose_name="Note")),
                (
                    "tracking_code",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tracking Code"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="shop.order",
                verbose_name="Order",
            ),
        ),
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("CART", "Cart"),
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("CONFIRMED", "Confirmed"),
                            ("SHIPPED", "Shipped"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                            ("REFUNDED", "Refunded"),
                            ("RETURNED", "Returned"),
                        ],
                        max_length=20,
                        verbose_name="From Status",
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("CART", "Cart"),
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("CONFIRMED", "Confirmed"),
                            ("SHIPPED", "Shipped"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                            ("REFUNDED", "Refunded"),
                            ("RETURNED", "Returned"),
                        ],
                        max_length=20,
                        verbose_name="To Status",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Note")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="shop.order",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Status History",
                "verbose_name_plural": "Order Status Histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="Amount"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("REFUNDED", "Refunded"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("ONLINE", "Online"),
                            ("CREDIT", "Credit"),
                            ("CASH_ON_DELIVERY", "Cash on Delivery"),
                        ],
                        default="ONLINE",
                        max_length=20,
                        verbose_name="Payment Type",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("ZARINPAL", "Zarinpal"),
                            ("MELLAT", "Mellat"),
                            ("SAMAN", "Saman"),
                            ("PARSIAN", "Parsian"),
                        ],
                        default="ZARINPAL",
                        max_length=20,
                        verbose_name="Payment Provider",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("IRR", "Iranian Rial"), ("IRT", "Iranian Toman")],
                        default="IRR",
                        max_length=3,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        help_text="Payment reference ID from the payment provider",
                        max_length=255,
                        verbose_name="Reference ID",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="shop.order",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="Amount"
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Transaction ID",
                    ),
                ),
                (
                    "provider_tracking_code",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Provider Tracking Code",
                    ),
                ),
                (
                    "provider_status",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Provider Status"
                    ),
                ),
                (
                    "provider_message",
                    models.TextField(blank=True, verbose_name="Provider Message"),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True,
                        help_text="Complete response from payment provider",
                        null=True,
                        verbose_name="Raw Response",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="shop.payment",
                        verbose_name="Payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Transaction",
                "verbose_name_plural": "Payment Transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "image",
                    models.ImageField(upload_to="shop/products/", verbose_name="Image"),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Alternative Text"
                    ),
                ),
                (
                    "is_feature",
                    models.BooleanField(default=False, verbose_name="Is Feature Image"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="shop.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
                "ordering": ["-is_feature", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Quantity"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        verbose_name="Price at Time of Purchase",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shop.order",
                        verbose_name="Order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="shop.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Item",
                "verbose_name_plural": "Order Items",
                "unique_together": {("order", "product")},
            },
        ),
    ]
