# Generated by Django 5.1.4 on 2025-03-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="max_age",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Maximum Age"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="min_age",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Minimum Age"
            ),
        ),
    ]
