# Generated by Django 5.1.4 on 2025-03-22 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_promocode_remove_order_note_order_notes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="shipping_address",
        ),
    ]
