# Generated by Django 5.2.1 on 2025-11-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_add_manual_payment_support"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("CART", "Cart"),
                    ("PENDING", "Pending"),
                    ("AWAITING_VERIFICATION", "Awaiting Verification"),
                    ("PROCESSING", "Processing"),
                    ("CONFIRMED", "Confirmed"),
                    ("SHIPPED", "Shipped"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                    ("REFUNDED", "Refunded"),
                    ("RETURNED", "Returned"),
                ],
                max_length=25,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="from_status",
            field=models.CharField(
                choices=[
                    ("CART", "Cart"),
                    ("PENDING", "Pending"),
                    ("AWAITING_VERIFICATION", "Awaiting Verification"),
                    ("PROCESSING", "Processing"),
                    ("CONFIRMED", "Confirmed"),
                    ("SHIPPED", "Shipped"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                    ("REFUNDED", "Refunded"),
                    ("RETURNED", "Returned"),
                ],
                max_length=25,
                verbose_name="From Status",
            ),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="to_status",
            field=models.CharField(
                choices=[
                    ("CART", "Cart"),
                    ("PENDING", "Pending"),
                    ("AWAITING_VERIFICATION", "Awaiting Verification"),
                    ("PROCESSING", "Processing"),
                    ("CONFIRMED", "Confirmed"),
                    ("SHIPPED", "Shipped"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                    ("REFUNDED", "Refunded"),
                    ("RETURNED", "Returned"),
                ],
                max_length=25,
                verbose_name="To Status",
            ),
        ),
    ]
