# Generated by Claude Code on 2025-12-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_alter_invoice_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("standard_post", "پست معمولی"),
                    ("express", "پیک موتوری"),
                ],
                max_length=25,
                null=True,
                verbose_name="Shipping Method",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_cost",
            field=models.PositiveIntegerField(default=0, verbose_name="Shipping Cost"),
        ),
    ]
