# Generated by Claude Code on 2025-12-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_add_shipping_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_visible",
            field=models.BooleanField(
                default=True,
                help_text="Controls whether this product is shown in the store",
                verbose_name="Is Visible",
            ),
        ),
    ]
